create table client (
    id bigint generated by default as identity,
    address varchar(255),
    age integer,
    dni varchar(255),
    gender varchar(255),
    name varchar(255),
    phone varchar(255),
    is_active boolean,
    password varchar(255),
    primary key (id));
create table account (
    id bigint generated by default as identity,
    client_id bigint,
    initial_amount numeric(38,2),
    is_active boolean,
    number varchar(255),
    type varchar(255),
    primary key (id));
create table transaction (
    id bigint generated by default as identity,
    amount numeric(38,2),
    balance numeric(38,2),
    date date,
    type varchar(255),
    account_id bigint,
    primary key (id));
alter table if exists transaction
    add constraint FK6g20fcr3bhr6bihgy24rq1r1b
    foreign key (account_id)
    references account;